image: Visual Studio 2017

version: 0.4.0

configuration: Release

install:
  - cmd: dotnet restore src\Chinchilla.sln

dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: $(appveyor_build_version)
  package_version: $(appveyor_build_version)

build:
  project: src\Chinchilla.sln
  publish_nuget: true

test_script:
  - ps: .\build\run-tests.ps1

deploy:
  provider: NuGet
  skip_symbols: true
  api_key:
    secure: token_etc
  artifact: '**\*.nupkg'
  on:
    appveyor_repo_tag: true
