image: Visual Studio 2017

configuration: Release

before_build:
  - cmd: dotnet restore src\Chinchilla.sln
  
build:
  project: src\Chinchilla.sln
  
test:
  assemblies:
    only:
      - 'targets\specifications\**\*.Specifications.dll'

artifacts:
  - path: targets\**\*.nupkg

deploy:
  provider: NuGet
  skip_symbols: true
  api_key:
    secure: token_etc
  artifact: targets\**\*.nupkg
  on:
    appveyor_repo_tag: true
