image: Visual Studio 2017

configuration: Release

install:
  - cmd: dotnet restore src\Chinchilla.sln

dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: $(appveyor_build_version)
  package_version: $(appveyor_build_version)

build:
  project: src\Chinchilla.sln
  publish_nuget: true
  
test:
  assemblies:
    only:
      - 'targets\specifications\**\*.Specifications.dll'

artifacts:
  - path: targets\**\*.nupkg

deploy:
  provider: NuGet
  skip_symbols: true
  api_key:
    secure: token_etc
  artifact: targets\**\*.nupkg
  on:
    appveyor_repo_tag: true
