image: Visual Studio 2017

configuration: Release

before_build:
  - cmd: dotnet restore src\Chinchilla.sln
  
build:
  project: src\Chinchilla.sln
  
test:
  assemblies:
    only:
      - 'targets\specifications\**\*.Specifications.dll'
